---
bazarr_api_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    31313862373534623333623134383861613637633736626164306431633839303066366635346461
    6562666661373636656362643262303366323935313839630a643734353632346230326263633432
    65383962353034303635386262643735303061303235393139323466623363643634633461343964
    6133363134616430350a643639626463633265633832373265313063333336333238366238366138
    31303361373866663239376139646261346636636533383361396430613133373565613161353336
    6665326334636465343730363530333538316166613766663231
    
emby_api_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34633966616531363364666461656234396332666366306237666537613931626635386364613735
    6263653264353332666166396535616433343839373133610a643737623437373666623635396262
    63303538353438323164306263313937616261656534303661326430353135666438653962656138
    6438383236373266320a613236303363336261666331376337646333353839373064303964663963
    62653436643033316631616661623464646335386366313364643763323934383036613935353561
    6166363838386466336237613737363639336134326432353138

sonarr_api_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    31343130333937643434653434323263383765313836323832366563303064343038373936353233
    6163363066313237663938653165626536353964643764330a353330643133386363366430313932
    66393133666366366432666437383966343665393665393734326164313964383065366234386231
    3264663936336438640a393964313632373937376339623935663266326138333137663532343666
    64326436393962393039663834633333343462363730343365353763356463653564386563383035
    6132386631613466393531666635646462383661343838666335
    
radarr_api_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32643930613163306165653935303164343164643035363234613266636538376262646237666561
    3839383338386131613836663337633462386531363537620a653763656434366333336639656535
    34336332343335666136336132306162386461383233316439623931373533333436363363336630
    3632613361326239370a316366363132353762313966353832373130653930616164656633396539
    39653938306531346232323264633435333631616536333339653535653462353764646264616234
    3163653536336161653039343161343531386633303364343736
    
prowlarr_api_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    37613631373561386436316666313337333361656130646464353765613032393238636636353465
    6132306337666132323738653035666439653266653937660a333364343336643062333538313735
    65386563643362626133313163333965653233366236393738643933316562326364643161363166
    6130643763653239370a643533323966336563306563343038623163323361323239616234663033
    65326565643636626231333431323833643966636363613433626234346163643732386634613739
    3064636566663037333336303633633932353231303862656236
    
unifi_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32363463653163373361303565303631363035663631633364316335353230626532343432333266
    6465613433326366613331343165663866656462623532300a313537653263633465613362326133
    31643632303834343835316466623939393836313730326632623238346431613361616537666164
    6333653730383535620a323030333430326463366633646336313132366535636537373232653633
    37343964633437393133626263373939346662653963666633663231613737333936

paperless_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32396338316231326334643433653239333663653763303435356334663531373764396530363933
    3337633162363465396239353833303866383663336232330a643462326462333862336535333537
    35336334343039643732393261326634343965303161666361386130333066396436666164373066
    3336343562363832310a613238646236366136613961326531666536623463393731353637306662
    6163

pihole_api_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    36666662623737366230623864366164613135656134343363396632646533656339346139343037
    6461623333656463663561366162383766633133323638300a316166633536653666353966343030
    63613631643865376366383137656638346539633061646131383631653666353538613930346436
    6264333431613538380a336236623935343235633636313666613166656433353033303337646336
    31626162343636323933613833646238613661386535323366613765366165336531656332653832
    65386162363763353664303563373031643337363161656538303037623361663632313136396566
    63646634643737326461363939646236303037336262313436303761366136623864373037326331
    38313564346331336435

gatus_discord_webhook: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34396535336363636265636333396433636637613037653838363661336634613862336635393231
    6363636235376336396163386233353938386461343363300a653432626262343064653139666263
    63333235353636343632393834663539366166333162313735326364616634376566623365313262
    6234393739376230630a623334386262303266383739316162613863633035616564393638643463
    30613235323662666635643662623930376537306234326337613130333837666532336466346534
    66303731666332663939356232626433356263323566323165613932636564386334333536373162
    64393036663338653563343265613734303065343265633035653933303230653936393431666565
    32353438653364333036323163343538323766383832653735653964316333613264346163656531
    3662

mqtt_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    62383264393766356633386438396332646139373165383761643565316163616638336435306465
    3766656133343839313035613664376139396366303437630a303136396230363666326137346262
    35643130633436636136646436633838343536323831616433633739636266343362363139303461
    3838396162383130660a393630323862636431363839313565373638643063663462383764346239
    6237

immich_db_pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    62653337306566643865663238646433313764353261343237633436313236613438636138353531
    6365616365666562383230666265616162666438313861380a646535353962396366313435636261
    37616631623264663762663739643130393531386665323665613635666131363265316239646238
    3238636362383635350a393261616365373132373762316339633862356562333136663465623236
    3134

esphome_pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    38333436633261376637393330373439393430303366353665626562383838626165626439363237
    3434376530386166643565646565386563613561343633390a666433633335333936643166656231
    63373037653830333763626363383731663466353164633266623266616536656535623137616465
    6331663236303534660a383733653130396435323033633038646361653466316336313363666339
    6563

iot_ssid: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35363434616432636230363366333734333062316266343763636164653961633734343666336638
    3861663031306161386531323739373864623366633436340a346639316661316330613531316262
    33303030666663626666633734373630376330306331386636663963623164613464383138363532
    3838366362336434350a393236383530343264383932303339643764626166353963306631353831
    3239
    
iot_ssid_pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    33643366623864386666663137633164613964313361376139666130313161663434636464393839
    6533386465376132656462356365613266366436306539350a376565643132666336363661663966
    63376139353037666237353637383234663230663837343164316634353538666363316163356262
    3865623237333564320a376661336231363436393564343933363430383132303264396362633738
    3337

torguard_user: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    64616163633833363666376435356366363465643066613336376564316336313531633765343735
    3632356238396336353432363264323563353864613235320a623538633633373461356361316139
    35623862613133376265663363653761663431336431623537663330353337376236333363353336
    3137613565636462650a323531643065303035633034653534643331653937303264323963396538
    66313065373337666630333634646530643331636438326237653132613035623439

torguard_pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    38353631666164643563343437373731643434633039333162316466343437656333396435643835
    3831643039666661383330323064613031373031666237640a323430386135326233313430613930
    35356562663865396332643662386263663831623737326565643438336239393138356235666534
    3137643362383631320a633166353739393761346632613135316538613038313162383263623230
    3762

cups_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    31393062353061366335626361303863613031663334623633613162333636623838643230393535
    6438616132636262336539336230646131633264616132630a386436633734613832643239383038
    39363562396132663837323661663331333331623838333632363865303565396136313135616132
    3133666366333365390a626165623132363437306430343138626164326662386438393861393931
    3336

wud_discord_webhook: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35356436303438313933363661373564373932396237306265343839643265633635323334396231
    6430376331303135383338393331393834323735303561660a383332386130356338613266626538
    37653937623564616533643936393535333664613139323564393730363432653738643031316162
    6630383932353333310a343330663566656632646637636238616463343934633539396135663334
    38306530366530313639653337313737306139363638373839386661383034636566323230353064
    36623636646637303964343231323935666338396361353336396566353039333263373566303437
    33656136623537386465623639643631313963663038306432613761393765363666656461303565
    39393538646231346232303231623865373364333832623334313561613964656338656266333563
    34656566323836393134373835333432323037383130616533376531613135313134323630353061
    3866663263306232326539343931626434313933393962396463

docker_hub_username: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35376466326565633737323637656134363039393436366238616365343732396461323931366565
    3537613439613065613261633335653761366433313137660a303063643062653435383261666630
    34663135663766623861356563306633306339353266663233653365653537306661363330386339
    6466356630326632330a326532316565643962373538313763666265373561306466306662653661
    3363

docker_hub_api_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34306637363964323464386662323237393838643263373865636465613763373863326530323932
    3336323934363962626637656365656338363435646139650a343161316263356163373763653662
    64633732313232616234343433313738383664323932383136383436396538333435363166303638
    3435343333343666610a633135303730643430666430306466633731363965353439326438343631
    36356133633631323964333461623735353166646234633338343932306534396265386461623264
    3237366132613238646361623363353638333933643161633836

vault_admin_token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30343635333062303930653539653663313964656538336138316563326361333561316539653336
    3338326237346266303761383639666261663161393838620a386136636534656539313034373966
    39663831653339373630636630316638373262623732333033363864373935366434616338393035
    6263353361663433640a643262663261383061313336663061653765343538613833333932393666
    37633238653866616361376130626633303130363735646266636132383536323666313436363630
    66313236353037343934633133353233653531626161623734626232666366393030313061386438
    34313939623861333666393134373139343736346231393433393039316162643839626231343836
    30663238373562306265643663613335393332396338393532376437396562316665643435323962
    63366362303938346463636564663038336431333934626232343563646266323439616439353832
    3530326332326264653164326436616631316538303738613462

nextcloud_db_root_pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65313763663766643235376362663735663535323139633537663930313835396165343362373861
    6337643133366536613638323237633530313437303431360a333934303534363663646239356230
    63386362663064303962323863653932326363653962373639356431353332323336393431356532
    6434626264333936300a376364623633323934376136333231636561313538306663643136373034
    3865

nextcloud_db_pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    36316431323163366335313665663265333265666232326363393036663565306131633539313239
    6339643731363633343236343864343330363536303464650a646535333730373536663631666430
    39343263643761646535343137376366646565373438343035323638363539336162363133666638
    6664356664386535310a343334366166393334333434303632326235336264303538323165383662
    6536

paperless_secret_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    38646264373736626264663465323764386165656431323339386530346638633830356532346364
    3261663932633164353638646134313764343833336162620a363330623033333963353235663163
    63333231326665656563343932326530376237333036623031663265616235316334353161643738
    3766393931396238660a653462623235373963643836386365616535643539313865396638656138
    32326339666530353761346133633038373064663865616563343436303338313530393565333336
    62313938653035356634633664376632323365626332383637626436663435383339623366653565
    373635336366366538613165666131636562
    
rclone_pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    31643132306439303863393932373666316662333430376631646435616532316164393361323464
    3835313134613131316166373132336136366561616261340a303939306336303166333334366635
    65393163303264396236366539666633373364623639353566646161346636356530396561663831
    6337616237346537370a653931643638313837656435656563653663623138346439626536626666
    3136

docker_browser_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34363439323437653735326566313439333037396166366434363235333535663764653731623836
    6661313030643966376235336436363638326639353061640a633165633531396661396234653934
    66313530653535656462303132333566666665663532623136646439396137626662396137353562
    3336386566376632390a306464303838306339623336613339333761316539326239366132353133
    61333165363262333165323763633837623161623730316664623066633036623132393036613834
    32633237356461646664303564383662363464316465663738366437613864336531633337303266
    38383232616162383339386632313062316335346162303065616662373136303039326635376461
    30646137646632343536613165333063386662323337366665323135666432346465303062666336
    39656331386439366333343437326261653431303561333666363163366164633239626635306131
    65616230323437323637343034333062646265303361393164363465633465323531313761643531
    613130393866653666633032313136623039

wud_github_token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    64653334393134373039383039323333333931653763353739376561363037356465666262393633
    3138613335376361396637396435656661303136643535300a363539373131333862373564376136
    37373635316135633737303235323666306239396337653831356436346338373334653465306161
    6539656562333434610a636334663665333531633264386430656336343931313061326163646633
    31383764643033333063623866396635633965393030396139303063303765343835313862613439
    6137663931643231396535363731363839323032623566363165

lr_cam_auth: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35346238396135373165613165336261303637303930666365393065636432396335656433393737
    3966623561646538376630656438366438396437613866320a646266313937383235383665373464
    30343239623239633064653262346235396366396266646134393536313534313165333737323262
    3366336233343964330a346335383636643162646565303332643663353966313233623263323034
    64393833343362333733386364373265346635623639376461333866626265653232

hassio_token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    62373432383333653138396630396264353465633435306137396335613065353861363566623565
    3063623731303066303832376134626230646633323061360a656434623964353033346363643165
    32343863653230653335333666303666623162626336643531653061613563376134646534343530
    3966633266306336610a363061343239323232663565376366333933383438373030646637353966
    39643635663030303562363664633464323162653234613936306231333739646138376464313439
    65613266313334313631363338356437346662396239366465356635326235623039623138313433
    62623337633864363966386232383437663131653135313363303630653461643536366330656562
    34636432613438666331643432313938313435616132343766383237666539363838313735316232
    66623563303864633838646530623831653831393339623865363464663732363231653538613635
    63346639663362663461336137363762323033353062363465633336393164613062326137333966
    30346663383564316366633564633566666437313034626565613431636537333365313766386265
    37656531333433396665363662613161343238383536323233323766663037306134393035633865
    31336161353434393539346264333439303130663831373066643562303538656334

endurain_db_pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34366432643161653061646464333539313863373037643361663965613831633264613432333238
    3964323462363933616430626237333937333063356138390a613439313665396466333732393061
    37646637636332326437393536393366313336656138633939646466613461366533316230356539
    6631346638336635620a373566646362343630663834663839363964363530646537376263346536
    3566

endurain_secret_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    61386537303261656134636636656339613735626335643132313232643933333432376663636565
    3363346337333962363038336266323433643636333765300a643039346234356335343536663062
    35623861383066663637373961383532646630613465313238363966356461663534316666333836
    3533303236383436360a343130393531613532623235343835303836346433643932353532656536
    35353666333366396366663931393631323964666631396366323736326433653061646365373661
    65306634356661336565373462306333333237653265656635616136623064373661646537613530
    35356233653138303333356131623361353433663631393137666637383031313831343038393865
    61636637353936313536

endurain_fernet_key: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    36333266383063313566323839613863663466373435393136346531376362633433363834396461
    6536356434323338633263336233343761313464396264610a303631653665343030393630363439
    37313036616632663061323265613932656364363237636630313262396633326363353437333734
    3236383132636334370a333238643062376230656331346638376664353863646432666233626664
    62383535666233376332373834383535383365376431643730666635356664306336313165306537
    3738313433326137623461316635623166616437646231663263

garmin_username: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    62643339323530666530346361613163326163316661613964646536373135396630303732356538
    3330373063323630633531653431343436626631383031620a393433323436366530646536616562
    30383830306636313333613430636166363832323462613664613861383866616263326661626666
    3930373262623066660a386562383532336532376630353433353337346633653437666131646634
    32616666623962343635373866383836663132396437623633303737373635653133
    
garmin_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    33313530643462653565353638656332363638313263636264663138306333353235346333323332
    6330353161376361333032306562633764626462376635610a306561376536316630376166336331
    32626366383437343862646431313637613864336361313931303634636639623536636462396434
    3739663036376535300a393235356238386262333430623135636265623233616530613439336131
    6365
