services:
  base-service:
    restart: unless-stopped
    networks:
      - app_bridge
    environment:
      TZ: Asia/Hong_Kong
      PUID: '99'
      PGID: '100'
      UMASK: '022'
    labels:
      net.unraid.docker.managed: composeman
